# Generated by Django 5.1.4 on 2024-12-26 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер цеха')),
                ('name', models.CharField(max_length=255, verbose_name='Название цеха')),
                ('bolishi', models.CharField(max_length=255, verbose_name='Руководитель цеха')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('seal_number', models.CharField(max_length=255, verbose_name='Номер пломбы')),
                ('user', models.CharField(max_length=255, verbose_name='Пользователь')),
                ('head_of_department', models.CharField(max_length=255, verbose_name='Руководитель подразделения')),
                ('warehouse_manager', models.CharField(max_length=255, verbose_name='Зав. склада')),
                ('type', models.CharField(max_length=255, verbose_name='Тип орг.техники')),
                ('motherboard', models.CharField(max_length=255, verbose_name='Производитель МП')),
                ('motherboard_model', models.CharField(max_length=255, verbose_name='Модель МП')),
                ('CPU', models.CharField(max_length=255, verbose_name='Процессор')),
                ('generation', models.CharField(max_length=255, verbose_name='Поколение процессора')),
                ('frequency', models.CharField(max_length=255, verbose_name='Частота процессора')),
                ('HDD', models.IntegerField(default='-', verbose_name='Диск  HDD')),
                ('SSD', models.IntegerField(verbose_name='Диск  SSD')),
                ('disk_type', models.IntegerField(choices=[(0, 'sata-1'), (1, 'sata-2'), (2, 'sata-3'), (3, 'NVmE'), (4, 'M2')], verbose_name='Тип диска')),
                ('RAM_type', models.IntegerField(choices=[(1, 'DDR1'), (2, 'DDR2'), (3, 'DDR3'), (4, 'DDR4'), (5, 'DDR5')], verbose_name='Тип оперативки')),
                ('RAM_size', models.IntegerField(verbose_name='Размер оперативной памяти')),
                ('GPU', models.CharField(max_length=255, verbose_name='Видеокарта')),
                ('ipadresss', models.CharField(max_length=255, verbose_name='IPv4 адрес')),
                ('mac_adress', models.CharField(max_length=255, verbose_name='Физический(MAC) адрес')),
                ('printer', models.CharField(default='Нет', max_length=255, verbose_name='Принтер')),
                ('scaner', models.CharField(default='Нет', max_length=255, verbose_name='Сканер')),
                ('type_webcamera', models.CharField(default='Нет', max_length=255, verbose_name='Тип вебкамера')),
                ('model_webcam', models.CharField(default='Нет', max_length=255, verbose_name='Модель вебкамеры')),
                ('monitor', models.CharField(max_length=255, verbose_name='Монитор')),
                ('departament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.department', verbose_name='Цех')),
            ],
        ),
    ]
